name: Build and Test (Deploy) Next.js

on:
  push:
    branches:
      - main # Triggers when code is pushed to the main branch
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab     
jobs:
 build:
  runs-on: ubuntu-latest
  defaults:
      run:
        working-directory: ./frontend/web-app
  steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Install dependencies
      run: npm install

    - name: Build Next.js app
      run: npm run build

    - name: Run tests
      run: npm run test


